### PR TITLE
Build on Apple

### PR DESCRIPTION
**Pull request by jadonk**
Consider these changes for building on Macs.

### CODE REVIEW

**Comment by nandub** [comment]
@ungureanuvladvictor Do you have any comments about these changes?

**Comment by ungureanuvladvictor** [comment]
Without a codeless kext there is no point to bring them on. I tried to develop one but did not have much luck.

**Comment by ungureanuvladvictor** [comment]
@jadonk can you make this pull request for the branch osx ?

**Comment by ungureanuvladvictor** [comment]
Everything done in https://github.com/ungureanuvladvictor/BBBlfs/tree/osx

**Pull request closed without merging**
